---
network:
  ethernets:
    enp35s0:
      addresses:
      - 10.0.1.3/24
      - 10.0.1.100/32
      - 10.0.1.101/32
      - 10.0.1.102/32
      - 10.0.1.103/32
      routes:
        - to: default
          via: 10.0.1.1
      nameservers:
        addresses:
        - 208.67.222.222
        - 208.67.220.220
        search: []
  version: 2
