---
network:
  ethernets:
    eth0:
      dhcp4: no
  bridges:
    virbr0:
      interfaces: [ "eth0" ]
      addresses: [ "10.0.1.4/24" ]
      routes:
        - to: default
          via: 10.0.1.1
      nameservers:
        addresses: [ "10.0.1.5" ]
        search: [ "home.lab" ]
  version: 2
