---
config:
  limits.kernel.nofile: 65535
  limits.processes: 1024
  cloud-init.user-data: |
    #cloud-config
    ssh_authorized_keys:
      - ssh-ed25519 <>
description: Default LXD profile for containers
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: lvmp1
    type: disk
name: default
used_by: []
