---
config:
  limits.kernel.nofile: 65535
  limits.processes: 1024
  limits.cpu: 1
  limits.memory: 1GiB
  cloud-init.user-data: |
    #cloud-config
    users:
    - name: core
      groups: [ systemd-journal ]
      lock_passwd: True
      sudo: ["ALL=(ALL) NOPASSWD:ALL"]
      shell: /bin/bash
      ssh_authorized_keys:
      - ssh-ed25519 <>
description: Default LXD profile for containers
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: zfsp1
    size: 10GB
    type: disk
name: default
used_by: []
