---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp35s0:
      dhcp4: no
  bridges:
    lxdbr0:
      interfaces: [ enp35s0 ]
      addresses: [ 10.0.122.3/24 ]
      routes:
        - to: default
          via: 10.0.122.1
      nameservers:
        addresses: [ 10.0.122.1 ]
        search: [ home.lab ]
